//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wservicios/", ConfigurationName="Timbrado.FormasDigitales.WSForcogsa")]
    public interface WSForcogsa {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/Cancelacion_1Request", ReplyAction="http://wservicios/WSForcogsa/Cancelacion_1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Response Cancelacion_1(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/Cancelacion_1Request", ReplyAction="http://wservicios/WSForcogsa/Cancelacion_1Response")]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Response> Cancelacion_1Async(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/Cancelacion_2Request", ReplyAction="http://wservicios/WSForcogsa/Cancelacion_2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Response Cancelacion_2(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/Cancelacion_2Request", ReplyAction="http://wservicios/WSForcogsa/Cancelacion_2Response")]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Response> Cancelacion_2Async(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/AutenticarRequest", ReplyAction="http://wservicios/WSForcogsa/AutenticarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarResponse Autenticar(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/AutenticarRequest", ReplyAction="http://wservicios/WSForcogsa/AutenticarResponse")]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarResponse> AutenticarAsync(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/TimbrarRequest", ReplyAction="http://wservicios/WSForcogsa/TimbrarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarResponse Timbrar(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservicios/WSForcogsa/TimbrarRequest", ReplyAction="http://wservicios/WSForcogsa/TimbrarResponse")]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarResponse> TimbrarAsync(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsCancelacionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acuseField;
        
        private string codEstatusField;
        
        private folio[] foliosField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string acuse {
            get {
                return this.acuseField;
            }
            set {
                this.acuseField = value;
                this.RaisePropertyChanged("acuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codEstatus {
            get {
                return this.codEstatusField;
            }
            set {
                this.codEstatusField = value;
                this.RaisePropertyChanged("codEstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public folio[] folios {
            get {
                return this.foliosField;
            }
            set {
                this.foliosField = value;
                this.RaisePropertyChanged("folios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class folio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string estatusUUIDField;
        
        private string mensajeField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estatusUUID {
            get {
                return this.estatusUUIDField;
            }
            set {
                this.estatusUUIDField = value;
                this.RaisePropertyChanged("estatusUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsTimbradoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cfdiField;
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                this.cfdiField = value;
                this.RaisePropertyChanged("cfdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservicios/")]
    public partial class wsAutenticarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensajeField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ObjectType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] anyField;
        
        private string idField;
        
        private string mimeTypeField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("MimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("Encoding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RSAKeyValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
                this.RaisePropertyChanged("Modulus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
                this.RaisePropertyChanged("Exponent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyValueType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RSAKeyValueType[] rSAKeyValueField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", Order=0)]
        public RSAKeyValueType[] RSAKeyValue {
            get {
                return this.rSAKeyValueField;
            }
            set {
                this.rSAKeyValueField = value;
                this.RaisePropertyChanged("RSAKeyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string x509IssuerNameField;
        
        private string x509SerialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string X509IssuerName {
            get {
                return this.x509IssuerNameField;
            }
            set {
                this.x509IssuerNameField = value;
                this.RaisePropertyChanged("X509IssuerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string X509SerialNumber {
            get {
                return this.x509SerialNumberField;
            }
            set {
                this.x509SerialNumberField = value;
                this.RaisePropertyChanged("X509SerialNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private X509IssuerSerialType x509IssuerSerialField;
        
        private byte[] x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public X509IssuerSerialType X509IssuerSerial {
            get {
                return this.x509IssuerSerialField;
            }
            set {
                this.x509IssuerSerialField = value;
                this.RaisePropertyChanged("X509IssuerSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
                this.RaisePropertyChanged("X509Certificate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] xPathField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XPath", Order=0)]
        public string[] XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
                this.RaisePropertyChanged("XPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransformType[] transformsField;
        
        private DigestMethodType digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
                this.RaisePropertyChanged("Transforms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
                this.RaisePropertyChanged("DigestMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("DigestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
                this.RaisePropertyChanged("URI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethodType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HMACOutputLength", typeof(string), DataType="integer", Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethodType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
                this.RaisePropertyChanged("Algorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CanonicalizationMethodType canonicalizationMethodField;
        
        private SignatureMethodType signatureMethodField;
        
        private ReferenceType referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CanonicalizationMethodType CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
                this.RaisePropertyChanged("CanonicalizationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SignatureMethodType SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
                this.RaisePropertyChanged("SignatureMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignedInfoType signedInfoField;
        
        private byte[] signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private ObjectType[] objectField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
                this.RaisePropertyChanged("SignedInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
                this.RaisePropertyChanged("SignatureValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
                this.RaisePropertyChanged("KeyInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object", Order=3)]
        public ObjectType[] Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("Object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancelacion_1", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class Cancelacion_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] folios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] publicKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] privateKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public Cancelacion_1Request() {
        }
        
        public Cancelacion_1Request(string rfcEmisor, string fecha, string[] folios, byte[] publicKey, byte[] privateKey, string password, string token) {
            this.rfcEmisor = rfcEmisor;
            this.fecha = fecha;
            this.folios = folios;
            this.publicKey = publicKey;
            this.privateKey = privateKey;
            this.password = password;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancelacion_1Response", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class Cancelacion_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsCancelacionResponse @return;
        
        public Cancelacion_1Response() {
        }
        
        public Cancelacion_1Response(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsCancelacionResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancelacion_2", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class Cancelacion_2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] folios;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.SignatureType signatureType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public Cancelacion_2Request() {
        }
        
        public Cancelacion_2Request(string rfcEmisor, string fecha, string[] folios, OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.SignatureType signatureType, string token) {
            this.rfcEmisor = rfcEmisor;
            this.fecha = fecha;
            this.folios = folios;
            this.signatureType = signatureType;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancelacion_2Response", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class Cancelacion_2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsCancelacionResponse @return;
        
        public Cancelacion_2Response() {
        }
        
        public Cancelacion_2Response(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsCancelacionResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticar", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class AutenticarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public AutenticarRequest() {
        }
        
        public AutenticarRequest(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarResponse", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class AutenticarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsAutenticarResponse @return;
        
        public AutenticarResponse() {
        }
        
        public AutenticarResponse(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsAutenticarResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Timbrar", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class TimbrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public TimbrarRequest() {
        }
        
        public TimbrarRequest(string cfd, string token) {
            this.cfd = cfd;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimbrarResponse", WrapperNamespace="http://wservicios/", IsWrapped=true)]
    public partial class TimbrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsTimbradoResponse @return;
        
        public TimbrarResponse() {
        }
        
        public TimbrarResponse(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsTimbradoResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSForcogsaChannel : OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSForcogsaClient : System.ServiceModel.ClientBase<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa>, OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa {
        
        public WSForcogsaClient() {
        }
        
        public WSForcogsaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSForcogsaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSForcogsaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSForcogsaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Response OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.Cancelacion_1(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request request) {
            return base.Channel.Cancelacion_1(request);
        }
        
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsCancelacionResponse Cancelacion_1(string rfcEmisor, string fecha, string[] folios, byte[] publicKey, byte[] privateKey, string password, string token) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request();
            inValue.rfcEmisor = rfcEmisor;
            inValue.fecha = fecha;
            inValue.folios = folios;
            inValue.publicKey = publicKey;
            inValue.privateKey = privateKey;
            inValue.password = password;
            inValue.token = token;
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Response retVal = ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).Cancelacion_1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Response> OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.Cancelacion_1Async(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request request) {
            return base.Channel.Cancelacion_1Async(request);
        }
        
        public System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Response> Cancelacion_1Async(string rfcEmisor, string fecha, string[] folios, byte[] publicKey, byte[] privateKey, string password, string token) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_1Request();
            inValue.rfcEmisor = rfcEmisor;
            inValue.fecha = fecha;
            inValue.folios = folios;
            inValue.publicKey = publicKey;
            inValue.privateKey = privateKey;
            inValue.password = password;
            inValue.token = token;
            return ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).Cancelacion_1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Response OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.Cancelacion_2(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request request) {
            return base.Channel.Cancelacion_2(request);
        }
        
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsCancelacionResponse Cancelacion_2(string rfcEmisor, string fecha, string[] folios, OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.SignatureType signatureType, string token) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request();
            inValue.rfcEmisor = rfcEmisor;
            inValue.fecha = fecha;
            inValue.folios = folios;
            inValue.signatureType = signatureType;
            inValue.token = token;
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Response retVal = ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).Cancelacion_2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Response> OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.Cancelacion_2Async(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request request) {
            return base.Channel.Cancelacion_2Async(request);
        }
        
        public System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Response> Cancelacion_2Async(string rfcEmisor, string fecha, string[] folios, OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.SignatureType signatureType, string token) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.Cancelacion_2Request();
            inValue.rfcEmisor = rfcEmisor;
            inValue.fecha = fecha;
            inValue.folios = folios;
            inValue.signatureType = signatureType;
            inValue.token = token;
            return ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).Cancelacion_2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarResponse OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.Autenticar(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest request) {
            return base.Channel.Autenticar(request);
        }
        
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsAutenticarResponse Autenticar(string usuario, string contrasena) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarResponse retVal = ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).Autenticar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarResponse> OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.AutenticarAsync(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest request) {
            return base.Channel.AutenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarResponse> AutenticarAsync(string usuario, string contrasena) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.AutenticarRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            return ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).AutenticarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarResponse OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.Timbrar(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest request) {
            return base.Channel.Timbrar(request);
        }
        
        public OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.wsTimbradoResponse Timbrar(string cfd, string token) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest();
            inValue.cfd = cfd;
            inValue.token = token;
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarResponse retVal = ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).Timbrar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarResponse> OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa.TimbrarAsync(OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest request) {
            return base.Channel.TimbrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarResponse> TimbrarAsync(string cfd, string token) {
            OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest inValue = new OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.TimbrarRequest();
            inValue.cfd = cfd;
            inValue.token = token;
            return ((OKHOSTING.ERP.Local.Mexico.Facturacion.Timbrado.FormasDigitales.WSForcogsa)(this)).TimbrarAsync(inValue);
        }
    }
}
